/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "FRIENDLY_CAPTCHA_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FRIENDLY_CAPTCHA_SITEKEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FormHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FormsApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "SERVICE_DESK_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SERVICE_DESK_DOMAIN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SERVICE_DESK_USERNAME": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "VERIFICATION_FROM_EMAIL_ADDR": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}